---
- namespace: "tool-box"
- app_name: "toolbox"
- source_repository_url:
- source_repository_ref:
- ocp_version:

openshift_cluster_content:
- object: Environment Setup
  content:
  - name: Create Projects
    template: "https://raw.githubusercontent.com/redhat-cop/openshift-templates/v1.4.12/project-requests/create-project.yml"
    action: create
    params_from_vars:
      NAMESPACE: "{{ namespace }}"
      NAMESPACE_DISPLAY_NAME: "{{ namespace }}"
    tags:
      - project
- object: Builds
  content:
  - name: tool-box
    template: "{{ inventory_dir }}/../../docker-build-template.yml"
    params_from_vars:
      NAME: "{{ app_name }}"
      SOURCE_REPOSITORY_URL: "{{ source_repository_url }}"
      SOURCE_REPOSITORY_REF: "{{ source_repository_ref }}"
      OCP_VERSION: "{{ ocp_version }}"
      SOURCE_CONTEXT_DIR: tool-box
    namespace: "{{ namespace }}"
    tags:
      - tool-box
